# Generated by Django 5.2.3 on 2025-07-02 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_user_category_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ccreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#0d6efd', 'Blue'), ('#198754', 'Green'), ('#ffc107', 'Yellow'), ('#dc3545', 'Red')], default='#0d6efd', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
