# Generated by Django 5.2.3 on 2025-07-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_ccreated_at_alter_category_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='ccreated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.category'),
        ),
    ]
