# Generated by Django 5.2.3 on 2025-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_category_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
    ]
