# Generated by Django 5.2.3 on 2025-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='reminder_type',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='reminderlog',
            name='status',
            field=models.CharField(default='sent', max_length=10),
        ),
    ]
