# Generated by Django 5.2.3 on 2025-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reminderlog_message_reminderlog_reminder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='reminder_type',
            field=models.CharField(default='deadline', max_length=20),
        ),
    ]
